# Generated by Django 4.1.2 on 2022-10-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_transaction_calculated_transaction_datetime_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertation",
            name="source_transaction",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_in_convertation",
                to="booking.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="convertation",
            name="target_transaction",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_in_convertation",
                to="booking.transaction",
            ),
        ),
    ]
