# Generated by Django 4.1.2 on 2022-10-14 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_convertation_source_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cost",
            old_name="source_transacton",
            new_name="source_transaction",
        ),
        migrations.RenameField(
            model_name="cost",
            old_name="transacton",
            new_name="transaction",
        ),
        migrations.AddField(
            model_name="convertation",
            name="datetime",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
